# services exists to let pods communicate with each other and with the outside world
apiVersion: v1
kind: Service
metadata:
  name: posts-srv

spec:
  type: NodePort
  selector:
    app: posts # select pods that were labeled by the posts name
  ports:
    - name: posts # unimportant name
      protocol: TCP
      port: 4000 # a port for the service, this port will direct the traffic to the targetPort
      targetPort: 4000 # actual port that our application is listing for traffic on.
